spring:
  datasource:
    url: ENC(aFao71o9ldlCCkzdRoYl0tcQJsfvf8ck0rB7gYgWyA1i2moPOyJXWuF8oUNXiBNOH3QTgVG+8Wpk1j4m5rfYZJs3BQcjNC5cV/BogOTtxTSDBXTfGZECy11ethcZJyfjTs8mnGVtEsjWwBNBZA7H1w==)
    username: ENC(Ik19yiFEz8dvVKzkuMiICfE5T3xufGVc4UzHWG3wYLVfngRMz2iDe+ey98iVN+3N)
    password: ENC(Z2iZALEiBavdElhIo3qqESudwgynHrX+O53lh9QU7xs+oncHnCrnf47quY19fWC9)
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: ENC(UFr9jsstQUXkE0L1gOpavpW8ficsURrl+Jlqd2agF4jbwNfPFDNSht+ZEiT0GZ8n)
      port: ENC(LzRocVKJUH1rg2UQCdGGdoPl+vFHMtPXxwPPo28CcB081v1kqQJYAWob/KAHsbXg)
      database: ENC(hmYV4wI4u8Yt8901fGqHjM/r8+nS7POadbaMp7RLkCmCbuUpdo+9Z5ehXUyTOrW3)
#    elasticsearch:
#      url: ENC(dHnrYlFkPQ0t8ta7q5AccQN1mCmU9k2OvfL1JCImfb2WpjlYK3meE9CF2lYyvDx7l2Bb+wQpy/NhlnhqXE80ng==)
  cache:
    type: redis
  mail:
    host: ENC(5zTO/Vua9v8pButKVfO78RBnyTNgdLrWVtYbi2drpqyO7o9jPDkqjAdKvuxjzwSq)
    port: ENC(TJJdWLjwtMjzvV2e1pLsmQewXZhdc6W1HnyvUWl/GJMPAVIA7mvOd30U1Nrp6Y0M)
    protocol: smtps
    default-encoding: UTF-8
    username: ENC(xLC2K0owpwx5uU+sejzQzUwVm9Aq0BV/opy/V5An1s4O+3SZe0MWekI3WheoJo+f)
    password: ENC(5j3d7xSOR2s5/lSmUrhnsES+7upvl9/sPeh9orUv17p6wNt+6gizqM70kS04IUvmmFvj/ZWrGS3Mq3azQH6D9g==)
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

token-login:
  test: true

moe:
  encrypt-str-aes-key: ENC(ZB19gVuaDRtmP/tTQF0XZzsctHMgoFYQhVzaICdUpJszhUf3O5fla7gxRmLaxz4sj9jBT2uQehWPqMb7RMV+qA==)
  local-file-service:
    file-base-path: ENC(+C+U03cJ4M2YGHJ9CdiEhfhJpHlBUocY7fjVEna9thgpEny9kF7el0eS/YIh/6QXGW1lHr1ZE+Qf8XjaYIvtSefwBcNzgUZRRXhVPCu0kr8=)
    url-prefix: ENC(4Cuc/hnB0A/IFY0V/fPwlHWUjH0b8Gf1oG/HF94KVi7YNHy3TmFbPTmQ2aED31mz)
  video-base-path: ENC(9gldmgrDWt05D0b3Z+Otr6JQQuQVrPk4jgh0ecBrdZvSocdW8FD8UAv5bPd2F3dRvs79g4W3TO97+KOkCqkZJQ==)
  default-video-path: ENC(mLPyKWv6nkzgRw9O/Z+sCO+ySAtCNqsrUCM52oFldkLbjcLRA331RFQaI9tcySCoAQwXWrndfg7iFmhHyCED1I/6HCNHm9UeepK+uS07kA8=)
  bili-session: ENC(me9V3N1hgXE15/6TZYjZdeZkVBOes3UbShYY8voRO+bfLOf5PVaycVkvNIp76Twevxaq2N2flyGRmCZSET50D4pHWt9BeOTaK1vJ7R+ABxGAjOuQ7GT93OVWt7Mrfxmf3X2NdtgS3UjoQJs+06kL/yBa9UMjaql3Q8CCKqIPH+nWfuDnclTBWzfLGyw2aOl3qpl1by1q24eucpk4keMCTx27Y1A2kB8UAoTDeoFkmhGAbUfFkFJNsix8qyaZ1Yiaxdg2MUVIH6fkuesxN07LEj9Gxtf3rGWGF8HMBzMt5i4ywZrzcY0Da13fAU67bJ2xfQn/DsatfbG1RlfjQ9W16g==)
  bv-url: ENC(6OEhCxFPAiIxBxp4b3/SN6C3cFsRVM1iTJyJcb4R1eOqoPLIQ5z8At7T7XW9JbTi59u1s5JVfawtk408ONU4eA==)
  bv-proxy-prefix: ENC(NmW1qoburQh3azwzOevh63DX9iZ9GFe+Hj4qLRBDoHw+zwckwSFUIH+1ZBgloLAFsVXYbaQp7H0Kvd19bkI0gg==)
  proxy-prefix: ENC(0HLFwM/S9XpH+KsTUN2Kz82VTDxsXEGz8yfUZRJsyUTbCSgmx8lkZfEYHkxGcy12Dt9jzswstTuNAUBIN+cMGPFAnUusaUGP5F6JdlDzv2tW1zr783aWncUDkBTO9GNd7HdeWrbJH8kSq+cgqKCjDg==)
# 限制视频转码 redis key    moe:limit:transform_video 有值就行
# 轮播图    moe:recommend_carousel   写id，用分号隔开
# 公告     moe:announcement
#  [
#    "java.util.ArrayList",
#    [
#      {
#        "@class": "com.abdecd.moebackend.business.pojo.vo.notice.Notice",
#        "title": "先消也上西应资",
#        "content": "consequat tempor et est",
#        "date": "1998-11-01",
#        "hash": "4261148C"
#      }
#    ]
#  ]

ali:
  oss:
    enable: true
    access-key-id: ENC(UtIxANJsSNLIOUeHtCS3oGLa6sH0psBX51TBwUDQE+hVokyZas3BFdK+/Mplw0riD0mVKWCybvT0N4hGmB80wA==)
    access-key-secret: ENC(P5rLk1nZfLPxelY3SH6bTJXz7gVy3hwERra6Esl9Ns/d2jafNGcCMiE3/sy5ajJ9qb7XULjn8cCoH+oMp2Eb/Q==)
    bucket-name: ENC(QUI2Pu3KwswaUCOU7FMikGQWmYV/UYjp+/b+SxEZC3kYHMJkySySFVrdGAXfqQ01)
    endpoint: ENC(zZVXJaK9Y00XuZzZtGeYed+LGoiXMuFj59pbRDROeO3j4il0mWCxXg/i5NS2FgOCZ3yJ2umaxrjQhL3ex25bNw==)
    url-prefix: ENC(fM6NvCRPRWP2g2vPND0MgPNFxVVQwTsvYBbPQbwrYifDRpTHkLep5h+oVTlZRguuv+VkrThRnDq8BI2sU5QOMQ==)
    sts-region-id: ENC(N5qjPVACDnxWjCJT0Ah0EQyMOeiFvyuYrIaMG3A8XmMKTZ10wFDP0qQsmd194B4y)
    sts-endpoint: ENC(ZcTL7m6ZIgry/IPcOnQV2sCwaS7AqGgzPyPkyyR7Lf5ekBuV4fnROijIU1lRIpupMIx7ZRdwbKqpKbn6Su0itg==)
    sts-role-arn: ENC(vwwr7+kjGqVQrlBe7q2GEZa6JHr00LV3LpqW8Ef99UHXIgIRDeaSkcygT276KtTAbV5iCnGeVYDe5WPsDrkIA2ZZXM/ysOH5i2vkNdwswR8=)
    sts-duration-seconds: 900
    sts-max-size: 2_147_483_648 # 2GB
    watermark: ENC(8qC7cyAF/gKqSRYK9M6YCxBV42d58KZGXYf3Bq0mvC67e1gG+cCz9ANcNChfeRIr4/4Pz76sBGKel8Rayt3XCQ==)

# mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'base'
      paths-to-match: '/**'
      packages-to-scan: com.abdecd.moebackend.business.controller.base
    - group: 'backstage'
      paths-to-match: '/**'
      packages-to-scan: com.abdecd.moebackend.business.controller.backstage
