spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
  threads:
    virtual:
      enabled: true
server:
  http2:
    enabled: true
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456

moe:
  captcha-ttl-seconds: 300

token-login:
  jwt-ttl-seconds: 2592000 # 30天
  exclude-patterns:
    - /error
    - /doc.html/**
    - /swagger-ui.html/**
    - /v3/api-docs/**
    - /user/login
    - /user/login-by-email
    - /user/signup
    - /user/forget-password
    - /plain-user
    - /common/captcha
    - /common/verify-email
    - /common/image/**
    - /common/video/**
    - /common/public-key
    - /search
    - /search/suggestion
    - /video/danmaku
    - /video/comment
    - /video
    - /video-group
    - /video-group/type
    - /video-group/related
    - /video-group/recommend
    - /video-group/carousel
    - /video-group/hot-tags
    - /video-group/bangumi-index
    - /bangumi-video-group
    - /bangumi-video-group/contents
    - /bangumi-video-group/time-schedule
    - /plain-video-group
    - /plain-video-group/contents
    - /plain-video-group/check-pending
    - /statistic/video-group-data
    - /statistic/video-play-start
    - /feedback/add
    - /notice/list
