spring:
  profiles:
    active: dev
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
server:
  http2:
    enabled: true
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456

moe:
  captcha-ttl-seconds: 300

token-login:
  jwt-ttl-seconds: 604800 # 7天
  jwt-refresh-ttl-seconds: 86400 # 1天
  exclude-patterns:
    - /error
    - /doc.html/**
    - /swagger-ui.html/**
    - /v3/api-docs/**
    - /user/login
    - /user/login-by-email
    - /user/signup
    - /user/forget-password
    - /plain-user
    - /common/captcha
    - /common/verify-email
    - /common/image/**
    - /common/video/**
    - /common/public-key
    - /search
    - /search/suggestion
    - /video/danmaku
    - /video/comment
    - /video
